"""Streamlit interactive frontend for Multimodal Deep Researcher.

Implements an adaptive stateful layout:
- State 0 (Initial): Prominent, centered Hero ingestion canvas on the main viewport.
- State 1 (Post-Processing): File uploader migrates to the sidebar; main canvas showcases
  the multi-tab analytical study dashboard (Knowledge Graph, Flashcards, Timeline, Summary).
"""

import json
import os
from typing import Any
import requests
import streamlit as st

from src.frontend.components.visualizers import (
    _get_val,
    render_flashcards,
    render_mind_map,
    render_timeline,
)

# --- Page Configuration ---
st.set_page_config(
    page_title="Multimodal Deep Researcher",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Backend URL configuration
DEFAULT_BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")

# --- Session State Initialization ---
if "has_data" not in st.session_state:
    st.session_state["has_data"] = False
if "dashboard_data" not in st.session_state:
    st.session_state["dashboard_data"] = None
if "analyzed_filename" not in st.session_state:
    st.session_state["analyzed_filename"] = None
if "backend_url" not in st.session_state:
    st.session_state["backend_url"] = DEFAULT_BACKEND_URL


def check_backend_health(url: str) -> bool:
    """Check whether the FastAPI backend is online and reachable."""
    try:
        resp = requests.get(f"{url}/health", timeout=2.0)
        return resp.status_code == 200 and resp.json().get("status") == "healthy"
    except Exception:
        return False


def execute_synthesis(uploaded_file: Any, custom_prompt: str, backend_url: str) -> None:
    """Send uploaded file and prompt to the FastAPI backend and update session state."""
    if not check_backend_health(backend_url):
        st.error(
            f"❌ Unable to connect to backend at `{backend_url}`. "
            "Please ensure the FastAPI service is running: `uvicorn src.backend.main:app --port 8000`"
        )
        return

    with st.spinner(
        f"🧠 Analyzing '{uploaded_file.name}' via Gemini 3.6 Flash...\n\n"
        "• Uploading to Gemini Files API\n"
        "• Polling file state until ACTIVE\n"
        "• Synthesizing Knowledge Graph, Flashcards & Timeline"
    ):
        try:
            files = {
                "file": (
                    uploaded_file.name,
                    uploaded_file.getvalue(),
                    uploaded_file.type or "application/octet-stream",
                )
            }
            data = {"prompt": custom_prompt.strip()} if custom_prompt.strip() else {}

            response = requests.post(
                f"{backend_url}/api/analyze",
                files=files,
                data=data,
                timeout=300,  # 5-minute timeout for large videos/PDFs
            )

            if response.status_code == 200:
                st.session_state["dashboard_data"] = response.json()
                st.session_state["analyzed_filename"] = uploaded_file.name
                st.session_state["has_data"] = True
                st.toast("✅ Intelligence synthesis complete!", icon="🎉")
                st.rerun()
            elif response.status_code == 429:
                st.error("⏳ Rate limit reached on Gemini API. Please wait a minute and retry.")
            elif response.status_code == 504:
                st.error("⏱️ Gateway Timeout: File processing took longer than expected on Gemini's servers.")
            else:
                detail = response.json().get("detail", response.text)
                st.error(f"❌ Analysis failed (HTTP {response.status_code}): {detail}")

        except requests.exceptions.ConnectionError:
            st.error(f"❌ Failed to reach backend at `{backend_url}`. Check server terminal.")
        except requests.exceptions.Timeout:
            st.error("⏱️ Request timed out after 300 seconds.")
        except Exception as exc:
            st.error(f"❌ Unexpected error occurred: {exc}")


def reset_dashboard() -> None:
    """Clear analysis data and return to State 0."""
    st.session_state["dashboard_data"] = None
    st.session_state["analyzed_filename"] = None
    st.session_state["has_data"] = False
    st.rerun()


def format_as_markdown(dashboard_data: dict) -> str:
    """Format the raw dashboard JSON payload into a clean, readable Markdown study guide.

    Args:
        dashboard_data: Raw JSON payload dictionary stored in session state.

    Returns:
        Structured, comprehensive Markdown string.
    """
    title = dashboard_data.get("title", "Research Study Synthesis")
    lines: list[str] = [
        f"# {title}",
        "",
        "> *Autonomous Synthesis generated by Multimodal Deep Researcher (Powered by Google Gemini 3.6 Flash)*",
        "",
        "---",
        "",
        "## 📝 Executive Summary",
        "",
    ]

    exec_summary = dashboard_data.get("executive_summary", {})
    if isinstance(exec_summary, str):
        lines.extend([exec_summary, ""])
    elif isinstance(exec_summary, dict):
        overview = exec_summary.get("overview")
        if overview:
            lines.extend(["### Overview", "", overview, ""])

        objectives = exec_summary.get("core_objectives", [])
        if objectives:
            lines.extend(["### Core Objectives", ""])
            for obj in objectives:
                lines.append(f"- {obj}")
            lines.append("")

        methodology = exec_summary.get("methodology")
        if methodology:
            lines.extend(["### Methodology & Technical Frameworks", "", methodology, ""])

        conclusions = exec_summary.get("primary_conclusions", [])
        if conclusions:
            lines.extend(["### Primary Conclusions", ""])
            for conc in conclusions:
                lines.append(f"- {conc}")
            lines.append("")

    # Key Findings
    findings = dashboard_data.get("key_findings", [])
    if findings:
        lines.extend(["## 🎯 Key Findings & Insights", ""])
        for finding in findings:
            lines.append(f"- {finding}")
        lines.append("")

    # Active-Recall Flashcards
    flashcards = dashboard_data.get("flashcards", [])
    if flashcards:
        lines.extend(["## 🗂️ Active-Recall Study Flashcards", ""])
        for idx, card in enumerate(flashcards, start=1):
            q = _get_val(card, "question", "Untitled Question")
            a = _get_val(card, "answer", "No answer provided.")
            topic = _get_val(card, "topic", "General")
            difficulty = str(_get_val(card, "difficulty", "medium")).capitalize()
            source = _get_val(card, "source_reference")

            lines.append(f"### Flashcard {idx}: {q}")
            meta_parts = [f"**Topic:** `{topic}`", f"**Difficulty:** `{difficulty}`"]
            if source:
                meta_parts.append(f"**Source Reference:** *{source}*")
            lines.append(" | ".join(meta_parts))
            lines.append("")
            # Blockquote for flashcard answers as required
            for ans_line in a.splitlines():
                lines.append(f"> {ans_line}")
            lines.append("")

    # Chronological & Phase Timeline
    timeline = dashboard_data.get("timeline", [])
    if timeline:
        lines.extend(["## ⏳ Chronological & Phase Timeline", ""])
        for event in timeline:
            period = _get_val(event, "date_or_period", "Milestone")
            event_title = _get_val(event, "title", "Milestone")
            summary = _get_val(event, "summary", "")
            significance = _get_val(event, "significance", "")
            sources = _get_val(event, "sources", [])

            lines.append(f"### [{period}] {event_title}")
            if summary:
                lines.extend(["", summary])
            if significance:
                lines.extend(["", f"- **Significance:** {significance}"])
            if sources:
                lines.append(f"- **Sources:** {', '.join(sources)}")
            lines.append("")

    lines.append("---")
    lines.append("*Exported from Multimodal Deep Researcher*")
    return "\n".join(lines)


# ==============================================================================
# STATE 0: INITIAL (HERO CENTRIC VIEWPORT)
# ==============================================================================
if not st.session_state.get("has_data", False) or st.session_state.get("dashboard_data") is None:

    # Minimal diagnostic sidebar in State 0
    with st.sidebar:
        st.markdown(
            """
            <div style="text-align: center; margin-bottom: 20px;">
                <h2 style="margin: 0; color: #8B5CF6; font-size: 1.5rem;">🔬 Deep Researcher</h2>
                <p style="color: #94A3B8; font-size: 0.82rem; margin: 4px 0 0 0;">Autonomous Multimodal Intelligence</p>
            </div>
            """,
            unsafe_allow_html=True,
        )

        backend_online = check_backend_health(st.session_state["backend_url"])
        if backend_online:
            st.success("🟢 Backend Connected", icon="✅")
        else:
            st.warning(
                "🔴 Backend Offline\n\nStart backend via:\n`uvicorn src.backend.main:app --reload --port 8000`",
                icon="⚠️",
            )

        st.divider()

        with st.expander("⚙️ Connection Settings", expanded=False):
            new_url = st.text_input("Backend API URL", value=st.session_state["backend_url"], key="state0_backend_url")
            if new_url != st.session_state["backend_url"]:
                st.session_state["backend_url"] = new_url.rstrip("/")
                st.rerun()

        st.caption("Powered by Google Gemini 3.6 Flash & FastAPI")

    # Main Centered Hero Viewport
    st.markdown(
        """
        <div style="text-align: center; padding: 32px 16px 20px 16px; max-width: 900px; margin: 0 auto;">
            <span style="background: rgba(139, 92, 246, 0.15); border: 1px solid rgba(139, 92, 246, 0.4); color: #C4B5FD; font-size: 0.8rem; font-weight: 700; padding: 6px 14px; border-radius: 20px; text-transform: uppercase; letter-spacing: 0.05em;">
                Gemini 3.6 Flash Multi-Tier Engine
            </span>
            <h1 style="color: #F8FAFC; font-size: 3rem; font-weight: 800; margin: 16px 0 10px 0; letter-spacing: -0.02em;">
                🔬 Multimodal Deep Researcher
            </h1>
            <p style="color: #94A3B8; font-size: 1.15rem; line-height: 1.6; max-width: 720px; margin: 0 auto 24px auto;">
                Autonomous research synthesis engine. Decompose academic manuscripts, video lectures, and technical audio into interactive 
                <b style="color: #A78BFA;">Knowledge Graphs</b>, <b style="color: #38BDF8;">Active-Recall Flashcards</b>, and <b style="color: #34D399;">Chronological Milestones</b>.
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # Hero Center Upload Card
    hero_col_left, hero_col_center, hero_col_right = st.columns([1, 6, 1])
    with hero_col_center:
        st.markdown(
            """
            <div style="background: #131C31; border: 1px solid #1E293B; border-radius: 14px; padding: 24px 28px 12px 28px; margin-bottom: 24px; box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.3);">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
                    <h3 style="margin: 0; color: #F8FAFC; font-size: 1.25rem;">📤 Ingest Research Asset</h3>
                    <div style="display: flex; gap: 8px;">
                        <span style="background: #1E293B; color: #94A3B8; font-size: 0.72rem; padding: 3px 8px; border-radius: 6px;">PDF</span>
                        <span style="background: #1E293B; color: #94A3B8; font-size: 0.72rem; padding: 3px 8px; border-radius: 6px;">MP4</span>
                        <span style="background: #1E293B; color: #94A3B8; font-size: 0.72rem; padding: 3px 8px; border-radius: 6px;">MP3</span>
                        <span style="background: #1E293B; color: #94A3B8; font-size: 0.72rem; padding: 3px 8px; border-radius: 6px;">TXT</span>
                    </div>
                </div>
            """,
            unsafe_allow_html=True,
        )

        hero_uploaded_file = st.file_uploader(
            "Upload research document, lecture video, audio, or notes",
            type=["pdf", "mp4", "mp3", "txt"],
            help="Select an academic paper, symposium presentation, audio lecture, or notes.",
            key="hero_uploader",
            label_visibility="collapsed",
        )

        hero_custom_prompt = st.text_area(
            "🎯 Research Focus & Queries (Optional)",
            placeholder="e.g. Focus on theoretical frameworks, experimental methodologies, error thresholds, and causal mechanisms...",
            help="Provide specific inquiries or themes to steer the synthesis.",
            height=90,
            key="hero_prompt",
        )

        hero_analyze_btn = st.button(
            "🚀 Synthesize Research",
            type="primary",
            use_container_width=True,
            disabled=hero_uploaded_file is None,
            key="hero_btn",
        )

        st.markdown("</div>", unsafe_allow_html=True)

        if hero_analyze_btn and hero_uploaded_file is not None:
            execute_synthesis(hero_uploaded_file, hero_custom_prompt, st.session_state["backend_url"])

    # Capabilities Row Below Hero
    st.markdown("<br/>", unsafe_allow_html=True)
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        st.markdown(
            """
            <div style="background: #131C31; padding: 20px; border-radius: 10px; border-top: 3px solid #8B5CF6; border-left: 1px solid #1E293B; border-right: 1px solid #1E293B; border-bottom: 1px solid #1E293B; height: 100%;">
                <h4 style="color: #F8FAFC; margin: 0 0 8px 0; font-size: 1.05rem;">🧠 Knowledge Graph</h4>
                <p style="color: #94A3B8; font-size: 0.88rem; line-height: 1.5; margin: 0;">Force-directed topological network of concepts and causal relationships with interactive physics.</p>
            </div>
            """,
            unsafe_allow_html=True,
        )
    with c2:
        st.markdown(
            """
            <div style="background: #131C31; padding: 20px; border-radius: 10px; border-top: 3px solid #10B981; border-left: 1px solid #1E293B; border-right: 1px solid #1E293B; border-bottom: 1px solid #1E293B; height: 100%;">
                <h4 style="color: #F8FAFC; margin: 0 0 8px 0; font-size: 1.05rem;">🗂️ Active Flashcards</h4>
                <p style="color: #94A3B8; font-size: 0.88rem; line-height: 1.5; margin: 0;">Spaced-repetition study units with difficulty tags, conceptual probes, and exact source citations.</p>
            </div>
            """,
            unsafe_allow_html=True,
        )
    with c3:
        st.markdown(
            """
            <div style="background: #131C31; padding: 20px; border-radius: 10px; border-top: 3px solid #F59E0B; border-left: 1px solid #1E293B; border-right: 1px solid #1E293B; border-bottom: 1px solid #1E293B; height: 100%;">
                <h4 style="color: #F8FAFC; margin: 0 0 8px 0; font-size: 1.05rem;">⏳ Chrono Timeline</h4>
                <p style="color: #94A3B8; font-size: 0.88rem; line-height: 1.5; margin: 0;">Sequential progression of discoveries, experimental phases, and quantified milestone significance.</p>
            </div>
            """,
            unsafe_allow_html=True,
        )
    with c4:
        st.markdown(
            """
            <div style="background: #131C31; padding: 20px; border-radius: 10px; border-top: 3px solid #EC4899; border-left: 1px solid #1E293B; border-right: 1px solid #1E293B; border-bottom: 1px solid #1E293B; height: 100%;">
                <h4 style="color: #F8FAFC; margin: 0 0 8px 0; font-size: 1.05rem;">📑 Executive Brief</h4>
                <p style="color: #94A3B8; font-size: 0.88rem; line-height: 1.5; margin: 0;">Incisive high-impact findings, core theses, and experimental takeaways extracted with academic rigor.</p>
            </div>
            """,
            unsafe_allow_html=True,
        )


# ==============================================================================
# STATE 1: POST-PROCESSING (WORKSPACE DASHBOARD VIEWPORT)
# ==============================================================================
else:
    dashboard: dict[str, Any] = st.session_state["dashboard_data"]
    title = dashboard.get("title", "Research Study Synthesis")
    source_name = st.session_state.get("analyzed_filename", "Uploaded Asset")

    # In State 1, the file uploader relocates to the left sidebar for continuous research
    with st.sidebar:
        st.markdown(
            """
            <div style="text-align: center; margin-bottom: 16px;">
                <h2 style="margin: 0; color: #8B5CF6; font-size: 1.4rem;">🔬 Deep Researcher</h2>
                <p style="color: #94A3B8; font-size: 0.82rem; margin: 4px 0 0 0;">Autonomous Multimodal Intelligence</p>
            </div>
            """,
            unsafe_allow_html=True,
        )

        backend_online = check_backend_health(st.session_state["backend_url"])
        if backend_online:
            st.success("🟢 Backend Connected", icon="✅")
        else:
            st.warning("🔴 Backend Offline", icon="⚠️")

        st.divider()

        # Study Guide Export
        raw_filename = st.session_state.get("analyzed_filename") or "document"
        base_filename = os.path.splitext(os.path.basename(raw_filename))[0] or raw_filename
        markdown_data = format_as_markdown(dashboard)
        st.download_button(
            label="📥 Download Study Guide (.md)",
            data=markdown_data,
            file_name=f"study_guide_{base_filename}.md",
            mime="text/markdown",
            use_container_width=True,
            key="download_study_guide_md",
        )

        st.download_button(
            label="📦 Export Dashboard JSON",
            data=json.dumps(dashboard, indent=2),
            file_name=f"research_dashboard_{base_filename}.json",
            mime="application/json",
            use_container_width=True,
            key="download_study_dashboard_json",
        )

        st.divider()

        # Reset action button to return to State 0
        if st.button("🔄 New / Reset Analysis", use_container_width=True):
            reset_dashboard()

        st.divider()

        # Relocated File Ingestion for subsequent studies
        st.markdown("### 📤 Ingest Next Asset")
        sidebar_file = st.file_uploader(
            "Upload new material",
            type=["pdf", "mp4", "mp3", "txt"],
            help="Ingest another document, symposium video, or audio track.",
            key="sidebar_uploader",
        )

        sidebar_prompt = st.text_area(
            "🎯 Research Focus (Optional)",
            placeholder="e.g. Focus on theoretical derivations...",
            help="Custom inquiries for the new document.",
            height=85,
            key="sidebar_prompt",
        )

        sidebar_analyze_btn = st.button(
            "🚀 Re-Synthesize",
            type="primary",
            use_container_width=True,
            disabled=sidebar_file is None,
            key="sidebar_btn",
        )

        if sidebar_analyze_btn and sidebar_file is not None:
            execute_synthesis(sidebar_file, sidebar_prompt, st.session_state["backend_url"])

        st.divider()

        with st.expander("⚙️ Connection Settings", expanded=False):
            new_url = st.text_input("Backend API URL", value=st.session_state["backend_url"], key="state1_backend_url")
            if new_url != st.session_state["backend_url"]:
                st.session_state["backend_url"] = new_url.rstrip("/")
                st.rerun()

        st.caption("Powered by Google Gemini 3.6 Flash & FastAPI")

    # Main Workspace Dashboard
    st.markdown(
        f"""
        <div style="background: linear-gradient(135deg, #1E1B4B 0%, #0F172A 100%); padding: 24px 28px; border-radius: 14px; border: 1px solid #3730A3; margin-bottom: 24px; box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.4);">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
                <span style="background: #4F46E5; color: #FFFFFF; font-size: 0.75rem; font-weight: 700; padding: 4px 12px; border-radius: 20px; text-transform: uppercase; letter-spacing: 0.05em;">Synthesized Study</span>
                <span style="color: #94A3B8; font-size: 0.85rem;">🤖 Engine: <b style="color: #C4B5FD;">Gemini 3.6 Flash</b></span>
            </div>
            <h1 style="margin: 6px 0 10px 0; color: #F8FAFC; font-size: 2.2rem; font-weight: 800; letter-spacing: -0.01em;">{title}</h1>
            <p style="margin: 0; color: #94A3B8; font-size: 0.95rem;">📄 Source: <b style="color: #E2E8F0;">{source_name}</b></p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # Analytical Tabs
    tab_summary, tab_mindmap, tab_flashcards, tab_timeline = st.tabs(
        [
            "📑 Executive Summary",
            "🧠 Knowledge Graph (Mind Map)",
            "🗂️ Flashcards",
            "⏳ Timeline & Milestones",
        ]
    )

    # --- Tab 1: Executive Summary ---
    with tab_summary:
        col1, col2 = st.columns([2, 1])

        with col1:
            exec_summary = dashboard.get("executive_summary", {})
            if isinstance(exec_summary, str):
                st.markdown("### 📝 Research Overview")
                st.markdown(
                    f"""
                    <div style="background: #131C31; border: 1px solid #1E293B; border-radius: 10px; padding: 18px 22px; font-size: 0.98rem; color: #E2E8F0; line-height: 1.6; margin-bottom: 20px;">
                        {exec_summary}
                    </div>
                    """,
                    unsafe_allow_html=True,
                )
            else:
                # 1. Overview
                overview_text = _get_val(exec_summary, "overview", "")
                if overview_text:
                    st.markdown("### 📝 Research Overview")
                    st.markdown(
                        f"""
                        <div style="background: #131C31; border: 1px solid #1E293B; border-radius: 10px; padding: 18px 22px; font-size: 0.98rem; color: #E2E8F0; line-height: 1.6; margin-bottom: 20px;">
                            {overview_text}
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )

                # 2. Core Objectives
                objectives = _get_val(exec_summary, "core_objectives", [])
                if objectives:
                    st.markdown("### 🎯 Core Objectives")
                    for obj in objectives:
                        st.markdown(
                            f"""
                            <div style="display: flex; align-items: flex-start; gap: 10px; margin-bottom: 10px; background: #131C31; border: 1px solid #1E293B; border-radius: 8px; padding: 10px 14px;">
                                <span style="color: #8B5CF6; font-size: 1.1rem; line-height: 1.4;">▪</span>
                                <span style="color: #F1F5F9; font-size: 0.95rem; line-height: 1.5;">{obj}</span>
                            </div>
                            """,
                            unsafe_allow_html=True,
                        )
                    st.markdown("<div style='margin-bottom: 16px;'></div>", unsafe_allow_html=True)

                # 3. Methodology & Technical Frameworks
                methodology_text = _get_val(exec_summary, "methodology", "")
                if methodology_text:
                    st.markdown("### 🔬 Methodology & Frameworks")
                    st.markdown(
                        f"""
                        <div style="background: #131C31; border: 1px solid #1E293B; border-left: 4px solid #38BDF8; border-radius: 8px; padding: 16px 20px; font-size: 0.95rem; color: #E2E8F0; line-height: 1.6; margin-bottom: 20px;">
                            {methodology_text}
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )

                # 4. Primary Conclusions
                conclusions = _get_val(exec_summary, "primary_conclusions", [])
                if conclusions:
                    st.markdown("### 🏁 Primary Conclusions")
                    for conc in conclusions:
                        st.markdown(
                            f"""
                            <div style="display: flex; align-items: flex-start; gap: 10px; margin-bottom: 10px; background: #131C31; border: 1px solid #1E293B; border-radius: 8px; padding: 10px 14px;">
                                <span style="color: #10B981; font-size: 1.1rem; line-height: 1.4;">✔</span>
                                <span style="color: #F1F5F9; font-size: 0.95rem; line-height: 1.5;">{conc}</span>
                            </div>
                            """,
                            unsafe_allow_html=True,
                        )
                    st.markdown("<div style='margin-bottom: 16px;'></div>", unsafe_allow_html=True)

        with col2:
            st.markdown("### 🎯 Key Findings & Insights")
            findings = dashboard.get("key_findings", [])
            if findings:
                for idx, finding in enumerate(findings, start=1):
                    st.markdown(
                        f"""
                        <div style="background: #131C31; border-left: 4px solid #10B981; border-top: 1px solid #1E293B; border-right: 1px solid #1E293B; border-bottom: 1px solid #1E293B; padding: 12px 16px; border-radius: 8px; margin-bottom: 12px; font-size: 0.95rem; color: #F1F5F9; line-height: 1.5;">
                            <b>{idx}.</b> {finding}
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )
            else:
                st.info("No explicit key findings extracted.")

            st.markdown("### 📊 Metrics Overview")
            m1, m2 = st.columns(2)
            with m1:
                st.metric("Concepts", len(dashboard.get("nodes", [])))
                st.metric("Flashcards", len(dashboard.get("flashcards", [])))
            with m2:
                st.metric("Connections", len(dashboard.get("edges", [])))
                st.metric("Milestones", len(dashboard.get("timeline", [])))

    # --- Tab 2: Knowledge Graph (Mind Map) ---
    with tab_mindmap:
        nodes = dashboard.get("nodes", [])
        edges = dashboard.get("edges", [])

        st.markdown(
            f"### 🧠 Conceptual Knowledge Graph ({len(nodes)} concepts, {len(edges)} connections)"
        )
        render_mind_map(nodes=nodes, edges=edges, height="700px")

    # --- Tab 3: Flashcards ---
    with tab_flashcards:
        flashcards = dashboard.get("flashcards", [])
        render_flashcards(flashcards=flashcards)

    # --- Tab 4: Timeline ---
    with tab_timeline:
        timeline_events = dashboard.get("timeline", [])
        render_timeline(timeline_events=timeline_events)
